{
  "notify_audit": true, 
  "timeout_h": null, 
  "creator": 12842, 
  "no_data_timeframe": 480, 
  "id": 156055, 
  "notify_no_data": true, 
  "renotify_interval": null, 
  "escalation_message": "", 
  "query": "max(last_4h):max:aws.ec2.cloudops.instance_count{!region:us-east-1} by {region} > 0", 
  "message": "## Description:\n {{region.name}}  should have no instances, any instances that exist are possibly fraudulent. <%= cloudops_non_critical_pagerduty %>  \n\n## Escalation Path:\n  None \n\n## Possible Causes:\n## Potential Solutions:\n\n##Feedback:\n Have feedback for this alert? [File an issue](https://github.com/pivotal-cf/datadog-config/issues/new)", 
  "name": "<%= environment %> CF: AWS has instance on  {{region.name}}"
}
